#! /usr/bin/env bash

test_folder=$1
target_folder="$(pwd)/test-reports"
[[ -d "$target_folder" ]] && rm -rf "$target_folder"
mkdir -p "$target_folder"
test_logfile="$target_folder/test.log"
echo "" >> "$test_logfile"

####################
#### Statistics ####
####################

function save_result() {
  echo -e "${1}" >> "$test_logfile"
}

function print_results() {
  while read line; do
    echo "$line"
  done < "$test_logfile"
}

function tail_log() {
  tail -f "$test_logfile" | cut -d '|' -f 1 &
}

#################
#### Asserts ####
#################

function assert_equals() { # assert that $1 is equal to $2
  if [[ "$1" -eq "$2" ]]; then
    save_result "\t\tSuccess|s|$(date +'%s')"
  else
    save_result "\t\tExpected $1 but got $2|f|$(date +'%s')"
  fi
}

function assert_none_empty() { # assert that $1 is not empty or only spaces
  if [[ -z "${1// }" ]]; then
    save_result "\t\tSuccess|s|$(date +'%s')"
  else
    save_result "\t\tValue was empty, when expecting nonEmpty|f|$(date +'%s')"
  fi
}


function assert_is_substring_of() { # assert that $1 is a substring of $2
  if [[ "$2" =~ $1 ]]; then
    save_result "\t\tSuccess|s|$(date +'%s')"
  else
    save_result "\t\t'$1' was not a substring of '$2'|f|$(date +'%s')"
 fi
}

######################
#### Test Running ####
######################

function execute_function() {
    message=$($1 2>&1)
    status=$?

    if [[ "$status" -gt 0 ]]; then
      save_result "\t\t|${1}:${message}|${status}|$(date +'%s')"
    fi
}

function check_file() {
  # todo sanitycheck the file
  local test_file=$1
  . "$test_file"

  save_result "$test_file|entering|$(date +'%s')"

  # Run setup function if defined
  grep -q '^function setup()' "$test_file" && execute_function "setup"

  sed -n 's/^function \(check_.*\)().*/\1/p' "$test_file" | while IFS= read -r test_name; do
    save_result "\t$test_name|entering|$(date +'%s')"
    execute_function "$test_name"
    save_result "\t$test_name|exiting|$(date +'%s')"
  done

  # Run cleanup if defined
  grep -q '^function cleanup()' "$test_file" && execute_function "cleanup"

  save_result "$test_file|exiting|$(date +'%s')"
}

function run_tests() {
  # generate a summary
  # create a rapport
  tail_log
  while IFS= read -r -d '' file; do
    (check_file "$file")
  done < <(find "$test_folder" -type f \( -name '*.bash' -or -name '*.sh' \) -print0)
}

#######################
#### Main handling ####
#######################

run_tests
